//  GENERATED by scripts/build-brand.mjs from scripts/brand/brand-colors.json — do not edit; change the JSON and rebuild.
// window.MW_BRAND — for colours set from JavaScript (Chart.js, canvas, SVG built in JS), where a
// CSS var() cannot be used. MW_BRAND.rgba(name, a) builds the same rgba() the stylesheets use.
(function () {
  var c = {"navy":"#1B3A4B","navy-dark":"#122A38","navy-light":"#2A4F63","cream":"#F7F6F3","cream-dark":"#EDE8E1","gold":"#C8860A","teal":"#16815F","text":"#1A1C1E","muted":"#6B7178"};
  var rgb = {"navy":"27, 58, 75","navy-dark":"18, 42, 56","navy-light":"42, 79, 99","cream":"247, 246, 243","cream-dark":"237, 232, 225","gold":"200, 134, 10","teal":"22, 129, 95","text":"26, 28, 30","muted":"107, 113, 120"};
  var B = {}; for (var k in c) B[k] = c[k];
  B.rgb = rgb;
  B.rgba = function (name, a) { return 'rgba(' + rgb[name] + ',' + a + ')'; };
  window.MW_BRAND = B;
})();
