#!/usr/bin/env node
// build-brand.mjs — generates every brand-colour output from scripts/brand/brand-colors.json, the
// single source of truth (2026-10-01, row 303). A new palette is: edit the JSON, run
//   npm run build-brand && npm run build-tailwind
// commit, and redeploy the functions that bundle _shared/brand-colors.ts (emails, the certificate)
// and `config push` the recovery template. Nothing else carries a brand hex value — the standing
// guard (verify-brand-colors) fails if one reappears anywhere outside these generated files.
//
// Generated (never hand-edit — they say so at the top):
//   ../brand-tokens.css                          CSS custom properties for every page
//   ../brand-colors.js                           window.MW_BRAND, for canvas / Chart.js / SVG built in JS
//   ../supabase/functions/_shared/brand-colors.ts   BRAND, for email HTML and the PDF certificate
//   ../supabase/templates/recovery.html          the auth recovery email, from brand/recovery.template.html
// `--check` regenerates in memory and exits 1 naming any generated file that is out of date.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(HERE, '..');
const SRC = path.join(HERE, 'brand', 'brand-colors.json');
const { colors } = JSON.parse(fs.readFileSync(SRC, 'utf8'));
const rgb = (hex) => { const h = hex.replace('#', ''); return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16)).join(', '); };
const names = Object.keys(colors);
const HEAD = (c) => c + ' GENERATED by scripts/build-brand.mjs from scripts/brand/brand-colors.json — do not edit; change the JSON and rebuild.';

const css = '/* ' + HEAD('') + ' */\n' +
  '/* Every page links this FIRST. --brand-X is the colour; --brand-X-rgb is its channels, for\n' +
  '   rgba(var(--brand-X-rgb), a). The :where() classes recolour inline SVG with ZERO specificity —\n' +
  '   exactly like the presentation attributes they replace, so any author rule (a state, an\n' +
  '   animation, a hover) still wins as it did before (row 303). */\n' +
  ':root {\n' + names.map((n) => '  --brand-' + n + ': ' + colors[n] + ';\n  --brand-' + n + '-rgb: ' + rgb(colors[n]) + ';').join('\n') + '\n}\n' +
  names.map((n) => ':where(.svg-stroke-' + n + ') { stroke: var(--brand-' + n + '); }\n:where(.svg-fill-' + n + ') { fill: var(--brand-' + n + '); }').join('\n') + '\n';

const js = '// ' + HEAD('') + '\n' +
  '// window.MW_BRAND — for colours set from JavaScript (Chart.js, canvas, SVG built in JS), where a\n' +
  '// CSS var() cannot be used. MW_BRAND.rgba(name, a) builds the same rgba() the stylesheets use.\n' +
  '(function () {\n' +
  '  var c = ' + JSON.stringify(colors) + ';\n' +
  '  var rgb = ' + JSON.stringify(Object.fromEntries(names.map((n) => [n, rgb(colors[n])]))) + ';\n' +
  '  var B = {}; for (var k in c) B[k] = c[k];\n' +
  '  B.rgb = rgb;\n' +
  '  B.rgba = function (name, a) { return \'rgba(\' + rgb[name] + \',\' + a + \')\'; };\n' +
  '  window.MW_BRAND = B;\n' +
  '})();\n';

const ts = '// ' + HEAD('') + '\n' +
  '// For colours that cannot be CSS variables: email HTML (clients ignore var()) and the PDF\n' +
  '// certificate. BRAND_RGB is the integer channels; pdf-lib takes rgb(r / 255, g / 255, b / 255).\n' +
  'export const BRAND = ' + JSON.stringify(colors, null, 2) + ' as const;\n' +
  'export const BRAND_RGB = ' + JSON.stringify(Object.fromEntries(names.map((n) => [n, rgb(colors[n]).split(', ').map(Number)]))) + ' as const;\n';

const tplPath = path.join(HERE, 'brand', 'recovery.template.html');
const outputs = {
  'brand-tokens.css': css,
  'brand-colors.js': js,
  'supabase/functions/_shared/brand-colors.ts': ts
};
if (fs.existsSync(tplPath)) {
  let html = fs.readFileSync(tplPath, 'utf8');
  html = html.replace(/%%BRAND:([a-z-]+)%%/g, (m, n) => { if (!colors[n]) throw new Error('recovery.template.html names an unknown brand colour: ' + n); return colors[n]; });
  outputs['supabase/templates/recovery.html'] = html;
}

const check = process.argv.includes('--check');
// --check runs inside a verification pass, where a host READ under supabase/functions restarts the
// edge runtime (row 255) and the runner's preload refuses it. So in --check mode the Edge Function
// output is read from git — the index first (a regenerated file is staged with the change), then
// HEAD — never from disk. A regeneration you have not staged therefore reads as STALE: stage it.
function readGenerated(rel, p) {
  if (check && rel.startsWith('supabase/functions/')) {
    for (const ref of [':' + rel, 'HEAD:' + rel]) {
      const r = spawnSync('git', ['show', ref], { cwd: ROOT, encoding: 'utf8', maxBuffer: 1 << 26 });
      if (r.status === 0) return r.stdout.replace(/\r\n/g, '\n');
    }
    return null;
  }
  return fs.existsSync(p) ? fs.readFileSync(p, 'utf8').replace(/\r\n/g, '\n') : null;
}
const stale = [];
for (const [rel, content] of Object.entries(outputs)) {
  const p = path.join(ROOT, rel);
  const cur = readGenerated(rel, p);
  if (cur !== content) {
    if (check) stale.push(rel);
    else { fs.writeFileSync(p, content); console.log('wrote ' + rel); }
  } else if (!check) console.log('unchanged ' + rel);
}
if (check) {
  if (stale.length) { console.log('BRAND BUILD: STALE — ' + stale.join(', ') + ' do not match scripts/brand/brand-colors.json; run `npm run build-brand`'); process.exit(1); }
  console.log('BRAND BUILD: up to date (' + Object.keys(outputs).length + ' generated files match the JSON)');
}
